### ISSUE TITLE
Breakpoint mixin improvements

### ISSUE THREAD

**Issue by HugoGiraudel** [Penguin-Library/penguin#2]
The `breakpoint` mixin could be made a bit more automatic and elegant like this. :)

Improvements:

* Query-agnostic (to allow `min-height` and `max-height` queries for instance)
* Emit a warning when using an unknown breakpoint
* Less repetitive code

```scss
@mixin breakpoint($breakpoint, $query: 'min-width') {
  $breakpoints: (
    'bp-small': $screen-xs-min,
    'bp-medium': $screen-sm-min,
    'bp-large': $screen-md-min,
    'bp-huge': $screen-lg-min,
  );

  @if map-has-key($breakpoints, $breakpoint) {
    @media (#{$query}: map-get($breakpoints, $breakpoint)) { @content; }
  } @else {
    @warn 'No breakpoint found for `#{$breakpoint}`. Allowed values are: #{map-keys($breakpoints)}.';
  }
}
```
