### ISSUE TITLE
Ellipsis mixin and display

### ISSUE THREAD

**Issue by HugoGiraudel** [Penguin-Library/penguin#3]
I don’t think it is the responsibility of the `ellipsis` mixin to set the `display` property, as it is somehow unrelated. I would remove it from the mixin, which has the positive side of making the mixin argument-less.

**Comment by JoanClaret** [comment]
Agree.

in fact, we can use it like this (included in helpers.scss):

```css
/**
 *  Text utilities
 */

.ellipsis {
  @include ellipsis();
}

.ellipsis-block {
  @include ellipsis();
  display: block;
}

```
Fixed, thank you again!
